version: '3'

services:

  aiohttp:
    build: .
    container_name: aiohttp
    volumes:
      - .:/app
    networks:
      - database_network
      - web_network
    depends_on:
      - postgres
    working_dir: /app
    stdin_open: true
    tty: true
    restart: on-failure:3
    command: bash -c "python -m pytest && python main.py"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    volumes:
        - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - aiohttp
    restart: on-failure:3
    networks:
      - web_network

  postgres:
    image: postgres:alpine
    container_name: postgres
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'gino'
    restart: on-failure:3
    networks:
      - database_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  database_network:
  web_network:

volumes:
  postgres_data:
